version: '3.8'

services:
  app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
